# Date reading

In [1]:
import pandas as pd
import pandas as pd
import calendar

#%pip install pandas

In [2]:
df = pd.read_csv('../../Datasets/fromclass/ecommerce_sales_data.csv')
df['price'].iloc[:5]
s = df['country'].value_counts()

s1 = s.astype(int).to_dict()
df['city'].value_counts().sort_values()
df['city'].isna().sum()
df['city'].nunique()
c = df['city']
c.sort_index()

round(df['price'].sort_values().idxmin())

pay_ord = df[['payment_method', 'order_status']]
# cancelled_count = (df['order_status'] == 'Cancelled').sum()
# print(cancelled_count)
pay_ord.sort_values('order_status').head(1)
cols = ['order_status', 'price', 'payment_method']
p = [df.columns.get_loc(c) for c in cols]
print(p)

[18, 8, 17]

In [3]:
if all(col in df.columns for col in ['payment_method', 'order_status', 'price']):
  selected_columns = df[['payment_method', 'order_status', 'price']]
else:
  selected_columns = df.iloc[:, [17,18,8]]


selected_columns.sort_values(by=['payment_method', 'order_status', 'price'])
df.iloc[:, [17,18,8]]

df.columns[1]

'customer_id'

In [4]:
# print(df.iloc[1:5, 1:4])
# print()
# print(df.loc[1:5, ['payment_method', 'price']])

co = ['payment_method', 'order_status', 'price']
idx = [df.columns.get_loc(c) for c in co]
print(idx)


# df.iloc[:, [17, 18, 8]].head(10)
# df[['payment_method', 'order_status', 'price']].head(10)
# df.loc[0:9, ['payment_method', 'order_status', 'price']]

[17, 18, 8]

In [5]:
df['product_name'].head(10)
df.iloc[0:5, 5:9]
df.iloc[:3, -3:]
df.loc[10:10, ['customer_name', 'price']]

p = df['price'] > 100
df.loc[p, 'price'].head(10)
(~p).sum()
# df.loc[p & (df['order_status']=='Shipped'), 'price'].head(10)
(~p).mean()*100
df[p].tail(10)
df[df['price'] > 100] [['customer_id', 'customer_name', 'price']].head(10)

   customer_id   customer_name   price
1    CUST-0293      Angela Lee  882.75
7    CUST-0172      John Davis  231.83
8    CUST-0047      Paul Jones  123.83
13   CUST-0166   Anna Thompson  165.99
15   CUST-0139  Angela Johnson  251.86
19   CUST-0047  Helen Thompson  134.14
20   CUST-0013    Angela Davis  172.63
23   CUST-0086    Andrew Jones  302.98
26   CUST-0046     James White  172.87
28   CUST-0043    James Martin  823.95

In [6]:
pay = df[['payment_method','total_amount']]
pp = pay['payment_method'] == 'PayPal'
df.loc[pp, ['payment_method','total_amount']]

pay[pp].sort_values(by='total_amount', ascending = False).head(10)

     payment_method  total_amount
445          PayPal       9592.80
1123         PayPal       8517.80
756          PayPal       7766.60
79           PayPal       7645.10
813          PayPal       7198.56
171          PayPal       7085.80
548          PayPal       6799.88
350          PayPal       6126.00
570          PayPal       5881.12
1095         PayPal       5550.18

In [7]:
ex = df[(df['price'] > 1900) & (df['category'] == 'Electronics')]
ex.loc[:, ['customer_name', 'customer_email', 'category','product_name']].head(10)
exo = df[(df['price'] > 1900) | (df['category'] == 'Electronics')]
exo.loc[:, ['customer_name', 'customer_email', 'category','product_name']].head(10)

,customer_name,customer_email,category,product_name
1,Angela Lee,angela.lee@email.com,Electronics,Dell Laptop
28,James Martin,james.martin@email.com,Electronics,Dell Laptop
37,Ashley Perez,ashley.perez@email.com,Electronics,iPad Air
43,Daniel Lopez,daniel.lopez@email.com,Electronics,Samsung Galaxy S23
45,Lisa Ramirez,lisa.ramirez@email.com,Electronics,MacBook Pro
62,Sarah Ramirez,sarah.ramirez@email.com,Electronics,iPad Air
64,Brenda Williams,brenda.williams@email.com,Electronics,Sony Headphones
68,Mark Hernandez,mark.hernandez@email.com,Electronics,Samsung Galaxy S23
70,Angela Wilson,angela.wilson@email.com,Electronics,iPad Air
71,Lisa Brown,lisa.brown@email.com,Electronics,MacBook Pro

In [8]:
spo = df.loc[(df['price'] > 50) & (df['quantity'] >= 2) & (df['price'] < 200)].head(10)
spo
# a = df.query('50 < price < 200 and quantity >=2')
# a.loc[:, ['customer_name','price','product_name']].head(10)

,order_id,customer_id,customer_name,customer_email,product_id,product_name,category,brand,price,quantity,total_amount,discount_percent,order_date,shipping_address,city,state,country,payment_method,order_status,customer_age
2,ORD-1044,CUST-0299,David Davis,david.davis@email.com,PROD-8623,Web Development,Books,McGraw-Hill,73.08,5,365.40,15.0,2024-05-10,7584 Park Rd,San Jose,CA,Australia,PayPal,Cancelled,24.0
6,ORD-1756,CUST-0101,Andrew Davis,andrew.davis@email.com,PROD-4952,Board Game,Toys,Mattel,57.92,4,231.68,20.0,2023-06-08,2344 Oak Ave,Chicago,IL,USA,Debit Card,Completed,44.0
8,ORD-1211,CUST-0047,Paul Jones,paul.jones@email.com,PROD-4634,Tennis Racket,Sports,NaN,123.83,5,619.15,NaN,2024-06-19,4793 Elm St,Fort Worth,TX,Germany,Apple Pay,Completed,70.0
13,ORD-1495,CUST-0166,Anna Thompson,anna.thompson@email.com,PROD-7044,Jeans,Clothing,Nike,165.99,5,829.95,25.0,2023-07-15,5085 Main St,Dallas,TX,USA,Bank Transfer,Pending,68.0
19,ORD-1424,CUST-0047,Helen Thompson,helen.thompson@email.com,PROD-2060,Dress,Clothing,Gap,134.14,4,536.56,25.0,2024-06-16,3762 Park Rd,Seattle,WA,Australia,Credit Card,Pending,NaN
26,ORD-1425,CUST-0046,James White,james.white@email.com,PROD-3088,Hoodie,Clothing,Nike,172.87,4,691.48,0.0,2024-04-05,6459 First St,Los Angeles,CA,Germany,Bank Transfer,Pending,68.0
29,ORD-1359,CUST-0126,Paul Sanchez,paul.sanchez@email.com,PROD-7102,Business Strategy,Books,Pearson,60.06,4,240.24,25.0,2024-01-29,3838 Oak Ave,Phoenix,AZ,Germany,Debit Card,Cancelled,75.0
30,ORD-1535,CUST-0013,James Martin,james.martin@email.com,PROD-5818,Web Development,Books,McGraw-Hill,53.53,2,107.06,10.0,2023-10-23,5229 Second Ave,New York,NY,USA,Apple Pay,Processing,31.0
32,ORD-1372,CUST-0212,Andrew Hernandez,andrew.hernandez@email.com,PROD-4875,LEGO Set,Toys,LEGO,54.37,5,271.85,0.0,2024-02-22,6769 Main St,Los Angeles,CA,UK,Debit Card,Completed,32.0
34,ORD-1903,CUST-0245,Emily Smith,emily.smith@email.com,PROD-3089,Yoga Mat,Sports,Under Armour,195.08,2,390.16,NaN,2023-10-29,4666 First St,Los Angeles,CA,UK,Bank Transfer,Shipped,65.0

In [9]:
df.loc[(df['price'].between(50 , 200)) & (df['quantity'] >=2),['customer_name','price','product_name']].head(10)

       customer_name   price       product_name
2        David Davis   73.08    Web Development
6       Andrew Davis   57.92         Board Game
8         Paul Jones  123.83      Tennis Racket
13     Anna Thompson  165.99              Jeans
19    Helen Thompson  134.14              Dress
26       James White  172.87             Hoodie
29      Paul Sanchez   60.06  Business Strategy
30      James Martin   53.53    Web Development
32  Andrew Hernandez   54.37           LEGO Set
34       Emily Smith  195.08           Yoga Mat

In [10]:
missing_values = df.copy()

missing_values.isnull().mean()*100
missing_values.isnull().sum().head(2)

order_id       0
customer_id    0
dtype: int64

In [11]:
drop = missing_values.dropna()
print(missing_values.shape)
drop.isna().sum()
print(drop.shape)
a= missing_values.isna().mean()*100

(1220, 20)
(768, 20)

In [12]:
# print(missing_values['customer_email'].head())
# missing_total_percent = df.isna().sum().sum() / (df.shape[0] * df.shape[1]) * 100
# print(missing_total_percent)
# missing_values = missing_values.dropna(subset=['customer_email'])
missing_values.isna().sum()
missing_values=missing_values.dropna(how='all')

missing_values.isna().sum()
missing_values=missing_values.fillna('Unknown')
missing_values.loc[:, 'shipping_address'].head(20)
# How = any and how = all can my oparation to fill in nun vlaues.

0     8944 Second Ave
1     8232 Second Ave
2        7584 Park Rd
3       8955 First St
4         6685 Elm St
5       4813 First St
6        2344 Oak Ave
7     9440 Second Ave
8         4793 Elm St
9        7105 Main St
10        7265 Elm St
11       4862 Oak Ave
12            Unknown
13       5085 Main St
14        6874 Elm St
15        6315 Elm St
16      8680 First St
17       1624 Oak Ave
18       8782 Oak Ave
19       3762 Park Rd
Name: shipping_address, dtype: object

In [13]:
fillnum = ['discount_percent','customer_age']
fillobject = ['customer_email','brand','shipping_address','']

fill = {col: 0 for col in fillnum} | {col: 'Anonymous Customer' for col in fillobject}

missing_values = missing_values.fillna(fill)

a=missing_values.loc[missing_values['customer_email'] =='Anonymous Customer', ['customer_email']]

a

Empty DataFrame
Columns: [customer_email]
Index: []