# Drop and manage duplicate values

In [305]:
# %pip install pandas
import pandas as pd
import pandas as pd

In [322]:
df = pd.read_csv('../../Datasets/fromclass/ecommerce_sales_data.csv')
df_dups = df.copy()

# keep_false = df_dups.duplicated(keep=False)
# sar = df_dups[keep_false]

# lee = sar['customer_name']=='Sarah Lee'
# sar[lee]
# df_dups.duplicated().sum()

s=df['customer_name']
# s.index = df['customer_name']
# a=s.loc['James Harris']
# a=s[(s >= 70) & (s <=75)]
# a['Books'].head(2).round().sum()
a1 = s[s.duplicated()]
a1.head(10)
df['customer_name'].value_counts()['Michael Harris']

np.int64(4)

In [307]:
d=df_dups.drop_duplicates(subset=['product_id'], keep='last')
d.duplicated().sum()
d.shape

(1112, 20)

In [308]:
exercise_df = df_dups.copy()
print('4 Remove duplicate row: ')
print(f' Before removing duplicates: {exercise_df.shape}')
no_dups_df = exercise_df.drop_duplicates()
print(f' After removing duplicates: {no_dups_df.shape}')
if 'order_date' in exercise_df.columns:
  exercise_df['order_date'] =  pd.to_datetime(exercise_df['order_date'])
  print(f'order_date typoe {exercise_df['order_date'].dtype}')
  print('Sample convert dates')
  print(exercise_df['order_date'].head())

else:
  print("'order_date' column not fould")

4 Remove duplicate row:
 Before removing duplicates: (1220, 20)
 After removing duplicates: (1200, 20)
order_date typoe datetime64[ns]
Sample convert dates
0   2023-11-11
1   2025-02-19
2   2024-05-10
3   2024-11-22
4   2024-07-31
Name: order_date, dtype: datetime64[ns]

In [309]:
# df_converted=df.copy()
# covert_df['price'] = covert_df['price'].astype(str)
# print(covert_df.dtypes)

In [310]:
df_converted = df.copy()

print(f"Original Type: {df_converted['order_date'].dtype}")
df_converted['order_date'] = pd.to_datetime(df_converted['order_date'])
print(f"New Type: {df_converted['order_date'].dtype}")
print(df_converted['order_date'].head())
print()
print(df[ 'order_date'].head())

Original Type: object
New Type: datetime64[ns]
0   2023-11-11
1   2025-02-19
2   2024-05-10
3   2024-11-22
4   2024-07-31
Name: order_date, dtype: datetime64[ns]

0    2023-11-11
1    2025-02-19
2    2024-05-10
3    2024-11-22
4    2024-07-31
Name: order_date, dtype: object

# Data Group by

In [311]:
groupby_df = df.copy()
category_groups = groupby_df.groupby('category')



category_sum = groupby_df.groupby('category')['total_amount'].sum()
category_sum.sort_values(ascending=False)

category
Electronics      594302.27
Home & Garden    141609.39
Sports            68575.07
Clothing          55612.36
Beauty            49194.19
Toys              28881.55
Books             24382.35
Name: total_amount, dtype: float64

In [312]:
price_sum = groupby_df.groupby('category')['price'].mean()
price_sum.sort_values(ascending=False).round(2)
groupby_df.groupby('category').size()

category
Beauty           195
Books            180
Clothing         175
Electronics      179
Home & Garden    173
Sports           148
Toys             170
dtype: int64

In [313]:
price_sum = groupby_df.groupby('category')['price'].agg(['count', 'mean','median','std']).round(2)
price_sum

               count     mean   median     std
category
Beauty           195    79.83    81.25   42.35
Books            180    45.14    45.19   18.89
Clothing         175   105.37   103.56   53.34
Electronics      179  1075.05  1130.61  545.45
Home & Garden    173   259.21   263.59  134.04
Sports           148   161.39   158.69   75.02
Toys             170    55.87    57.15   26.04

In [314]:
price_analysis = groupby_df.groupby ('category', as_index=False).agg(
count=('price', 'count'),
total=('price','sum'),
average=('price', 'mean'),
median=('price', 'median'),
min_price=('price', 'min'),
max_price=('price','max'),
std_dev=('price', 'std')
)
price_analysis.round(2)

,category,count,total,average,median,min_price,max_price,std_dev
0,Beauty,195,15566.40,79.83,81.25,8.15,149.10,42.35
1,Books,180,8124.38,45.14,45.19,10.23,79.89,18.89
2,Clothing,175,18440.22,105.37,103.56,15.99,199.96,53.34
3,Electronics,179,192433.47,1075.05,1130.61,50.33,1999.17,545.45
4,Home & Garden,173,44842.59,259.21,263.59,30.73,496.31,134.04
5,Sports,148,23885.57,161.39,158.69,20.15,299.76,75.02
6,Toys,170,9497.80,55.87,57.15,10.70,99.07,26.04

In [315]:
multi_col_agg = groupby_df.groupby ( 'category',as_index=False) .agg({
'price': ['mean','max','min' ],
'quantity': ['sum','mean' ],
'order_id': 'count'
})
multi_col_agg

        category        price                 quantity           order_id
                         mean      max    min      sum      mean    count
0         Beauty    79.827692   149.10   8.15      600  3.076923      195
1          Books    45.135444    79.89  10.23      545  3.027778      180
2       Clothing   105.372686   199.96  15.99      528  3.017143      175
3    Electronics  1075.047318  1999.17  50.33      557  3.111732      179
4  Home & Garden   259.205723   496.31  30.73      558  3.225434      173
5         Sports   161.388986   299.76  20.15      426  2.878378      148
6           Toys    55.869412    99.07  10.70      521  3.064706      170

In [316]:
multi_col_agg = (
groupby_df.groupby('category').agg(
avg_price=('price', 'mean'),
max_price=('price','max'),
min_price=('price','min'),
total_quantity=('quantity', 'sum'),
avg_quantity=('quantity','mean'),
order_count=('order_id','count')
))

multi_col_agg.columns = ['avg_price','max_price', 'min_price', 'total_quantity', 'avg_quantity', 'order_count']
multi_col_agg. reset_index (inplace=True)

multi_col_agg

,category,avg_price,max_price,min_price,total_quantity,avg_quantity,order_count
0,Beauty,79.827692,149.10,8.15,600,3.076923,195
1,Books,45.135444,79.89,10.23,545,3.027778,180
2,Clothing,105.372686,199.96,15.99,528,3.017143,175
3,Electronics,1075.047318,1999.17,50.33,557,3.111732,179
4,Home & Garden,259.205723,496.31,30.73,558,3.225434,173
5,Sports,161.388986,299.76,20.15,426,2.878378,148
6,Toys,55.869412,99.07,10.70,521,3.064706,170

In [317]:
multy_category = groupby_df.groupby(['city','category'])
multy_category['quantity'].sum().unstack(fill_value=0).round(2).reset_index()

category,city,Beauty,Books,Clothing,Electronics,Home & Garden,Sports,Toys
0,Austin,30,8,32,17,30,15,17
1,Charlotte,35,43,33,21,29,28,31
2,Chicago,43,23,20,19,55,13,34
3,Columbus,16,31,17,52,38,21,9
4,Dallas,24,47,30,24,46,26,19
5,Fort Worth,62,35,19,27,22,27,33
6,Houston,28,22,34,29,37,27,34
7,Indianapolis,42,46,12,62,11,17,42
8,Jacksonville,25,11,25,25,14,19,20
9,Los Angeles,48,26,28,35,27,34,33
10,New York,23,33,36,22,26,24,18
11,Philadelphia,55,32,35,41,33,37,31
12,Phoenix,33,31,29,40,27,23,31
13,San Antonio,29,37,41,42,34,31,42
14,San Diego,18,25,51,21,24,20,8
15,San Francisco,42,26,21,18,40,25,63
16,San Jose,32,45,28,36,17,24,28
17,Seattle,15,24,37,26,48,15,28

In [318]:
city_analysis = groupby_df.groupby ('city').agg({
'customer_name': 'nunique',
'order_id': 'count',
'price': 'mean'
}).round(2)

city_analysis.columns = ['Unique_Customers', 'Total_Orders', 'Avg_Order_Value']
city_analysis
top_categories = groupby_df.groupby(['city','price']) ['total_amount']. sum().sort_values(ascending=-False)
top_categories.reset_index().head(10)

           city    price  total_amount
0      San Jose  1918.56       9592.80
1       Chicago  1838.22       9191.10
2  Philadelphia  1807.18       9035.90
3  Indianapolis  1770.84       8854.20
4   Los Angeles  1749.01       8745.05
5     San Diego  1748.14       8740.70
6     Charlotte  1746.81       8734.05
7     Charlotte  1703.56       8517.80
8       Phoenix  1629.72       8148.60
9        Dallas  1553.32       7766.60

In [319]:
groupby_df['order_date'] = pd.to_datetime(groupby_df['order_date'], dayfirst=True)
groupby_df['month'] = groupby_df['order_date'].dt.month_name()

ValueError: unconverted data remains when parsing with format "%Y-%d-%m": "9", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.